### PR TITLE
Add veilid user and change permissions

### PR DESCRIPTION
**Pull request by JTruj1ll0923**
Again, this probably isn't the best way to do this. However, the general idea details the remaining steps to get this to build and run properly, it seems. This helps with #1.

### CODE REVIEW

**Comment by JTruj1ll0923** [comment]
Changed this to a draft just in case

**Comment by virtadpt** [comment]
That's pretty much what I did earlier.  +1 for this patch.

**Comment by socketwench** [comment]
I did some more research, and I don't think this is the right approach:  https://bbs.archlinux.org/viewtopic.php?pid=1261219#p1261219

What is the right approach I haven't figured out yet though.

**Comment by JTruj1ll0923** [comment]
Yep agreed. I couldn't find a distinct consensus on what's the best way to do it. That's why I kept this as a draft. The commands do work from my experience, but probably not the best way to go about it.

**Comment by socketwench** [comment]
I've reached out to the Arch forums: https://bbs.archlinux.org/viewtopic.php?pid=2116059#p2116059

**Pull request closed without merging**
